### ISSUE TITLE
Reset should respect defaultSizes

### ISSUE THREAD

**Issue by boyswan** [johnwalley/allotment#152]
Currently reseting sets an equal distribution, how can I pragmatically set/reset to defaultSizes?

**Comment by johnwalley** [comment]
Sounds related to #121. It has some issues with how it interacts with min/max sizes which is why it hasn't been merged yet.

An alternative would be to have `reset` use the defaultSizes prop if it is present.

As you're the second person to ask for functionality like this I'll make a decision at the weekend and get something merged in for you to use and provide feedback on.
