### ISSUE TITLE
Dynamically add and remove panes

### ISSUE THREAD

**Issue by vijaytv** [johnwalley/allotment#304]
Hello,
  Thanks for creating a great library.   

I am working on a POC to see if I can dynamically add and remove panes while also tracking any panes being resized and save any of those changes.  I have created a [Code sandbox ](https://codesandbox.io/s/wild-darkness-fls0e3?file=/src/App.js) for reference. 

Since adding a pane or removing a pane also triggers the onChange event,  I get into an endless rerender situation.  You can replicate this by clicking on the add button and then the remove button.  

Is there a way to avoid this condition?

**Comment by johnwalley** [comment]
Hi @vijaytv. Thanks for putting together the CodeSandbox!

I wonder if there might be an issue with your `handleChange` function. At first glance it looks like it might be updating the sizes of the root level panes in the state regardless of whether the `onChange` callback was called by the root component or a nested one.

Just a guess but it might be that the above, coupled with a possible race condition between `handleChange` and `handleAdd`/`handleRemove` might explain what we're seeing. If you were to use the callback function form of setState (like you do in `handleRemove`) it would guarantee one isn't overwriting the change the other is trying to make.

I can take a more detailed look at the weekend but I'd be interested in seeing if the two changes I've outlined would help:

1. Update the root sizes if the root component triggered the callback, and the nested sizes if the nested component triggered the callback
2. Use the callback for of setState in your event handlers

**Comment by johnwalley** [comment]
You have also uncovered an unrelated bug 😄

<img width="394" alt="Screenshot 2022-05-24 at 23 17 10" src="https://user-images.githubusercontent.com/981531/170141811-7dc7d014-44f4-4475-a2a8-11e47f1b744c.png">

The horizontal sash (the blue thing that appears on hover) is only half the width it should be. This is due to `text-align: center` being applied to `.App`. This is perfectly fine, but as it cascades down to the Allotment html components and css it causes the visual issue you see in the screenshot. I've created issue #306 to track its fix.

**Comment by vijaytv** [comment]
@johnwalley ,
  Thanks for the quick response.  Your answer helped.  I have updated  (and cleaned up) my code  for anybody else who might be interested. I just noticed the issue with the horizontal sash. I'll wait for the fix.

**Comment by johnwalley** [comment]
Super!

I've released a new version [1.14.1](https://github.com/johnwalley/allotment/releases/tag/v1.14.1) which fixes #306.
