### ISSUE TITLE
Could not make it work with basic set up

### ISSUE THREAD

**Issue by viniciuscr** [johnwalley/allotment#93]
I´ve just created a app using CRA, add the allotment dependency and copy/past the sample

`yarn create react-app my-app`  then ` yarn add allotment`
and changed the **src/App.js** to:

```javascript
import { Allotment } from "allotment";
import "allotment/dist/style.css";

function App() {
  return (
    <Allotment>
      <Allotment.Pane>
        <div>A simple div</div>
      </Allotment.Pane>
      <Allotment.Pane>
        <div>Just a div</div>
      </Allotment.Pane>
    </Allotment>
  );
}

export default App;
```

I´ve got a blank screen.
When adding the **vertical** prop (`<Allotment vertical>`) it renders the divs and a line between it, where I can not interact with.
![image](https://user-images.githubusercontent.com/808063/145922160-cc950e6d-71b4-4400-84a8-d63d16280b5a.png)

I am using 
Microsoft Edge
Version 96.0.1054.53 (Official build) (64-bit)
on  Windows 11

**Comment by johnwalley** [comment]
Hi @viniciuscr. Thanks for getting in touch.

Could I just check what the dimensions of the element you're putting the Allotment component inside are? If I recall correctly Create React App has a root div with no explicit height. This would force the allotment component to have height zero which isn't very useful.

If this is the case then I will add something to the README making it clear that the Allotment component will take its dimensions from its parent.

Otherwise, I might have to ask for a reproduction on something like Codepen.

Thanks!

**Comment by viniciuscr** [comment]
Hi @johnwalley .
It worked!
Adding height to the parent was the missing peace.
Yes, updating the README  would be  perfect.
Thanks a lot for the help and even more thanks for this lib, it will save me a lot of time and some headaches
